# Docker Compose configuration for IT Asset Management System
# This file defines the services needed to run the application

version: '3.8'

services:
  # PostgreSQL database service
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: itams
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data

  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Expose FastAPI port
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/itams
    depends_on:
      - postgres  # Wait for database to be ready
    volumes:
      - ./backend:/app  # Mount backend code for development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  # Run with auto-reload

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Expose React development server
    volumes:
      - ./frontend:/app  # Mount frontend code for development
      - /app/node_modules  # Preserve node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1  # Backend API URL with correct path
    depends_on:
      - backend  # Wait for backend to be ready

# Define named volumes for data persistence
volumes:
  postgres_data:  # PostgreSQL data volume 